apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2025-02-27T045344Z
  name: policy-exc-req-q6677i7444j-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
    - privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
    - check-seccomp-strict
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - local-path-provisioner-58cc7856b6-5zzv7
        namespaces:
        - local-path-storage
    - resources:
        kinds:
        - Deployment
        names:
        - local-path-provisioner
        namespaces:
        - local-path-storage
    - resources:
        kinds:
        - ReplicaSet
        names:
        - local-path-provisioner-58cc7856b6
        namespaces:
        - local-path-storage
