apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-29T092701Z
  name: policy-exc-req-l1133l2477d-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
    - privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: disallow-capabilities
    ruleNames:
    - adding-capabilities
    - autogen-adding-capabilities
  - policyName: restrict-automount-sa-token
    ruleNames:
    - autogen-validate-automountServiceAccountToken
    - validate-automountServiceAccountToken
  - policyName: restrict-volume-types
    ruleNames:
    - autogen-restricted-volumes
    - restricted-volumes
  - policyName: disallow-privileged-containers
    ruleNames:
    - autogen-privileged-containers
    - privileged-containers
  - policyName: disallow-host-namespaces
    ruleNames:
    - autogen-host-namespaces
    - host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-adding-capabilities-strict
    - autogen-require-drop-all
    - adding-capabilities-strict
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        names:
        - kindnet
        - kube-proxy
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - kube-controller-manager-test-control-plane
        - kube-scheduler-test-control-plane
        - kindnet-4kdb7
        - kube-apiserver-test-control-plane
        - coredns-6f6b679f8f-t9qjj
        - coredns-6f6b679f8f-vcjml
        - kube-proxy-v9jmm
        - etcd-test-control-plane
        namespaces:
        - kube-system
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-6f6b679f8f
        namespaces:
        - kube-system
