apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-25T091655Z
  name: policy-exc-req-j3214v6097p-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-automount-sa-token
    ruleNames:
    - autogen-validate-automountServiceAccountToken
    - validate-automountServiceAccountToken
  match:
    any:
    - resources:
        kinds:
        - ReplicaSet
        names:
        - nirmata-kube-controller-6c8995f466
        - otel-agent-5dcdf5fd8b
        namespaces:
        - nirmata
    - resources:
        kinds:
        - Pod
        names:
        - nirmata-kube-controller-6c8995f466-g4kqv
        - otel-agent-5dcdf5fd8b-4wk64
        namespaces:
        - nirmata
    - resources:
        kinds:
        - Deployment
        names:
        - otel-agent
        - nirmata-kube-controller
        namespaces:
        - nirmata
