apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-28T071517Z
  name: policy-exc-req-j9897b4308i-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: disallow-capabilities
    ruleNames:
    - adding-capabilities
    - autogen-adding-capabilities
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
    - autogen-privileged-containers
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - require-drop-all
    - autogen-adding-capabilities-strict
    - autogen-require-drop-all
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        names:
        - kube-proxy
        - aws-node
        - eks-pod-identity-agent
        namespaces:
        - kube-system
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-7bb495d866
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - aws-node-4qpks
        - coredns-7bb495d866-psm2b
        - eks-pod-identity-agent-56zkw
        - kube-proxy-97pv8
        - coredns-7bb495d866-bps8m
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
