apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-11-21T160341Z
  name: policy-exc-req-q2942m6200v-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - autogen-run-as-non-root
    - run-as-non-root
  - policyName: disallow-capabilities
    ruleNames:
    - adding-capabilities
    - autogen-adding-capabilities
  - policyName: restrict-automount-sa-token
    ruleNames:
    - validate-automountServiceAccountToken
    - autogen-validate-automountServiceAccountToken
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
    - autogen-privileged-containers
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - autogen-host-path
    - host-path
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - adding-capabilities-strict
    - autogen-adding-capabilities-strict
    - autogen-require-drop-all
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        names:
        - kindnet
        - kube-proxy
        namespaces:
        - kube-system
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-7c65d6cfc9
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - coredns-7c65d6cfc9-jcwp6
        - kube-proxy-phtpr
        - kube-controller-manager-test-control-plane
        - coredns-7c65d6cfc9-t55hk
        - etcd-test-control-plane
        - kube-apiserver-test-control-plane
        - kindnet-fbndd
        - kube-scheduler-test-control-plane
        namespaces:
        - kube-system
