apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-25T092111Z
  name: policy-exc-req-s1435q5731d-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: disallow-capabilities
    ruleNames:
    - autogen-adding-capabilities
    - adding-capabilities
  - policyName: restrict-automount-sa-token
    ruleNames:
    - validate-automountServiceAccountToken
    - autogen-validate-automountServiceAccountToken
  - policyName: restrict-volume-types
    ruleNames:
    - autogen-restricted-volumes
    - restricted-volumes
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
    - autogen-privileged-containers
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - autogen-host-path
    - host-path
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - autogen-require-drop-all
    - autogen-adding-capabilities-strict
    - require-drop-all
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-6f6b679f8f
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - coredns-6f6b679f8f-tdz6m
        - kube-proxy-2js7g
        - kube-controller-manager-tests-control-plane
        - coredns-6f6b679f8f-jv2lp
        - kube-apiserver-tests-control-plane
        - kube-scheduler-tests-control-plane
        - etcd-tests-control-plane
        - kindnet-dkf98
        namespaces:
        - kube-system
    - resources:
        kinds:
        - DaemonSet
        names:
        - kindnet
        - kube-proxy
        namespaces:
        - kube-system
