apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-29T071125Z
  name: policy-exc-req-h5501y6983o-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: disallow-capabilities
    ruleNames:
    - adding-capabilities
    - autogen-adding-capabilities
  - policyName: restrict-automount-sa-token
    ruleNames:
    - validate-automountServiceAccountToken
    - autogen-validate-automountServiceAccountToken
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
    - autogen-privileged-containers
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - require-drop-all
    - autogen-adding-capabilities-strict
    - autogen-require-drop-all
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-6f6b679f8f
        namespaces:
        - kube-system
    - resources:
        kinds:
        - DaemonSet
        names:
        - kindnet
        - kube-proxy
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - kindnet-slmsn
        - coredns-6f6b679f8f-s8dth
        - kube-proxy-6cwx4
        - kube-scheduler-new-change-control-plane
        - coredns-6f6b679f8f-bt5l6
        - kube-apiserver-new-change-control-plane
        - kube-controller-manager-new-change-control-plane
        - etcd-new-change-control-plane
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
