apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2025-03-14T061715Z
  name: policy-exc-req-c8020t4270l-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-automount-sa-token
    ruleNames:
    - autogen-validate-automountServiceAccountToken
    - validate-automountServiceAccountToken
  - policyName: disallow-capabilities-strict
    ruleNames:
    - autogen-require-drop-all
    - require-drop-all
  match:
    any:
    - resources:
        kinds:
        - Pod
        names:
        - local-path-provisioner-58cc7856b6-fwj4t
        namespaces:
        - local-path-storage
    - resources:
        kinds:
        - ReplicaSet
        names:
        - local-path-provisioner-58cc7856b6
        namespaces:
        - local-path-storage
    - resources:
        kinds:
        - Deployment
        names:
        - local-path-provisioner
        namespaces:
        - local-path-storage
